name: Generate and Deploy Docs

on:
  push:
    paths:
      - '**.c'  # Trigger only on pushes affecting .c files
  workflow_dispatch:  # Enable manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout zagros
        uses: actions/checkout@v4

      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

      - name: Generate Documentation
        run: doxygen Doxyfile  # Runs Doxygen; assumes Doxyfile is in the repo root and outputs to 'html/' folder

      - name: Deploy to zagros.github.io
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: |
          # Clone zagros.github.io using the token for authentication
          git clone https://${DEPLOY_TOKEN}@github.com/LinArcX/zagros.github.io ../zagros.github.io
          
          # Switch to the target branch in zagros.github.io (e.g., main or gh-pages)
          cd ../zagros.github.io
          git checkout master
          
          # docs/doxygen
          # Clear existing content in Repo B (or target folder) and copy new HTML
          #rm -rf ./doxygen/html/*  # Remove all files in root; adjust if you want to preserve some files or use a subfolder
          cp -r ../zagros/docs/* ./
          
          # Commit and push changes
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-update documentation from https://github.com/LinArcX/zagros commit ${{ github.sha }}"
          git push origin master  # Pushes to the main branch; change if using gh-pages
